service: SP-Node-Lambda-Functions
provider:
  name: aws
  region: ap-south-1
  runtime: nodejs18.x
  timeout: 30
  environment:
    JWT_SECRET: "iamworkinginheliosassoftwareengineer"
    CountryTable: Country
    TokenHistoryTable: TokenHistory
    StockTermTable: StockTerms
    UserCFTable: UserCF
    NewsTable: NewsRawData
    FilteredNews: FilteredNews
    #Lambdas

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:PutItem
            - dynamodb:UpdateItem
          Resource:
            - arn:aws:dynamodb:ap-south-1:332717545786:table/*
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: "*"
        - Effect: Allow
          Action:
            - aws-marketplace:ViewSubscriptions
            - aws-marketplace:Subscribe
          Resource: "*"
        - Effect: Allow
          Action:
            - bedrock:InvokeModel
          Resource: "*"

plugins:
  - serverless-offline

functions:
  getCountries:
    handler: handlers/country.get
    events:
      - http:
          path: countries
          method: get

  postToken:
    handler: Common/auth.tokengeneration
    events:
      - http:
          path: tokengeneration
          method: put

  getStockTerms:
    handler: handlers/stockTerm.get
    events:
      - http:
          path: stockterms
          method: get

  getStockCategory:
    handler: handlers/stockCategory.get
    events:
      - http:
          path: stockcategory
          method: get

  userFlow:
    handler: handlers/userFlow.get
    events:
      - http:
          path: userflow
          method: put
 
  getCountry:
    handler: handlers/country.getCountry
    events:
      - http:
          path: country
          method: get

  showTermAnalysis:
    handler: handlers/getAnalysis.showTermAnalysis
    events:
      - http:
          path: showtermanalysis
          method: get

  showCategoryAnalysis:
    handler: handlers/getAnalysis.showCategoryAnalysis
    events:
      - http:
          path: showcategoryanalysis
          method: get

  showSectorAnalysis:
    handler: handlers/getAnalysis.showSectorAnalysis
    events:
      - http:
          path: showsectoranalysis
          method: get

  showStockAnalysis:
    handler: handlers/getAnalysis.showStockAnalysis
    events:
      - http:
          path: showstockanalysis
          method: get
          
############# Externl Calls ##############

  getNews:
    handler: External/newsAnalysis.get
    timeout: 300
    description: "Fetches news data for a given country and date range"    
  
  gettermAnalysis:
    handler: External/termAnalysis.get
    timeout: 300
    description: "Generate the term analysis for a given country"

  getcategoryAnalysis:
    handler: External/categoryAnalysis.get
    timeout: 300
    description: "Generate the category analysis for a given country and term name"

  getsectorAnalysis:
    handler: External/sectorAnalysis.get
    timeout: 300
    description: "Generate the sector analysis for a given country, term name and category name"

  getstockAnalysis:
    handler: External/stockAnalysis.get
    timeout: 300
    description: "Generate the stock analysis for a given country, term name, category name and top three sectors"