service: SP-Node-Lambda-Functions
provider:
  name: aws
  region: ap-south-1
  runtime: nodejs18.x
  environment:
    JWT_SECRET: "iamworkinginheliosassoftwareengineer"
    CountryTable: Country
    TokenHistoryTable: TokenHistory
    StockTermTable: StockTerms
    UserCFTable: UserCF
    #Lambdas


  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:PutItem
            - dynamodb:UpdateItem
          Resource:
            - arn:aws:dynamodb:ap-south-1:332717545786:table/*
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: "*"


plugins:
  - serverless-offline

functions:
  getCountries:
    handler: handlers/country.get
    events:
      - http:
          path: countries
          method: get

  postToken:
    handler: Common/auth.tokengeneration
    events:
      - http:
          path: tokengeneration
          method: put

  getStockTerms:
    handler: handlers/stockTerm.get
    events:
      - http:
          path: stockterms
          method: get

  getStockCategory:
    handler: handlers/stockCategory.get
    events:
      - http:
          path: stockcategory
          method: get


  userFlow:
    handler: handlers/userFlow.get
    events:
      - http:
          path: userflow
          method: put

  TestouterCall:
    handler: handlers/test.apiHandler
    events:
      - http:
          path: invoke
          method: post
